# Generated by Django 3.1.6 on 2021-02-07 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='date published')),
                ('gender', models.CharField(choices=[('성별', '성별'), ('여성', '여성'), ('남성', '남성')], default='N', max_length=10, verbose_name='성별')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='본인 확인 이메일(선택사항)')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='휴대전화')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
