# Generated by Django 3.1.6 on 2021-02-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210208_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('성별', '성별'), ('남성', '남성'), ('여성', '여성')], default='N', max_length=10, verbose_name='성별'),
        ),
    ]
